### ISSUE TITLE
请问动画是否支持js钩子？ 

### ISSUE THREAD

**Issue by chbless** [Dafrok/san-transition#3]
在动画过程中是否可以添加js钩子函数？
例如vue是这样的

`
<transition
  v-on:before-enter="beforeEnter"
  v-on:enter="enter"
  v-on:after-enter="afterEnter"
  v-on:enter-cancelled="enterCancelled"

  v-on:before-leave="beforeLeave"
  v-on:leave="leave"
  v-on:after-leave="afterLeave"
  v-on:leave-cancelled="leaveCancelled"
>
`

**Comment by Dafrok** [comment]
JS 钩子画蛇添足了，s-transition 指令本来就是 JS 钩子
